//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: messages.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Protowire_RPCClient`, then call methods of this protocol to make API calls.
internal protocol Protowire_RPCClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Protowire_RPCClientInterceptorFactoryProtocol? { get }

  func messageStream(
    callOptions: CallOptions?,
    handler: @escaping (Protowire_KaspadResponse) -> Void
  ) -> BidirectionalStreamingCall<Protowire_KaspadRequest, Protowire_KaspadResponse>
}

extension Protowire_RPCClientProtocol {
  internal var serviceName: String {
    return "protowire.RPC"
  }

  /// Bidirectional streaming call to MessageStream
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  internal func messageStream(
    callOptions: CallOptions? = nil,
    handler: @escaping (Protowire_KaspadResponse) -> Void
  ) -> BidirectionalStreamingCall<Protowire_KaspadRequest, Protowire_KaspadResponse> {
    return self.makeBidirectionalStreamingCall(
      path: Protowire_RPCClientMetadata.Methods.messageStream.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageStreamInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Protowire_RPCClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Protowire_RPCNIOClient")
internal final class Protowire_RPCClient: Protowire_RPCClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Protowire_RPCClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Protowire_RPCClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the protowire.RPC service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Protowire_RPCClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Protowire_RPCNIOClient: Protowire_RPCClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Protowire_RPCClientInterceptorFactoryProtocol?

  /// Creates a client for the protowire.RPC service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Protowire_RPCClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Protowire_RPCAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Protowire_RPCClientInterceptorFactoryProtocol? { get }

  func makeMessageStreamCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncBidirectionalStreamingCall<Protowire_KaspadRequest, Protowire_KaspadResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Protowire_RPCAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Protowire_RPCClientMetadata.serviceDescriptor
  }

  internal var interceptors: Protowire_RPCClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeMessageStreamCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncBidirectionalStreamingCall<Protowire_KaspadRequest, Protowire_KaspadResponse> {
    return self.makeAsyncBidirectionalStreamingCall(
      path: Protowire_RPCClientMetadata.Methods.messageStream.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageStreamInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Protowire_RPCAsyncClientProtocol {
  internal func messageStream<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Protowire_KaspadResponse> where RequestStream: Sequence, RequestStream.Element == Protowire_KaspadRequest {
    return self.performAsyncBidirectionalStreamingCall(
      path: Protowire_RPCClientMetadata.Methods.messageStream.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageStreamInterceptors() ?? []
    )
  }

  internal func messageStream<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Protowire_KaspadResponse> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Protowire_KaspadRequest {
    return self.performAsyncBidirectionalStreamingCall(
      path: Protowire_RPCClientMetadata.Methods.messageStream.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageStreamInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Protowire_RPCAsyncClient: Protowire_RPCAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Protowire_RPCClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Protowire_RPCClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Protowire_RPCClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'messageStream'.
  func makeMessageStreamInterceptors() -> [ClientInterceptor<Protowire_KaspadRequest, Protowire_KaspadResponse>]
}

internal enum Protowire_RPCClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "RPC",
    fullName: "protowire.RPC",
    methods: [
      Protowire_RPCClientMetadata.Methods.messageStream,
    ]
  )

  internal enum Methods {
    internal static let messageStream = GRPCMethodDescriptor(
      name: "MessageStream",
      path: "/protowire.RPC/MessageStream",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Protowire_RPCProvider: CallHandlerProvider {
  var interceptors: Protowire_RPCServerInterceptorFactoryProtocol? { get }

  func messageStream(context: StreamingResponseCallContext<Protowire_KaspadResponse>) -> EventLoopFuture<(StreamEvent<Protowire_KaspadRequest>) -> Void>
}

extension Protowire_RPCProvider {
  internal var serviceName: Substring {
    return Protowire_RPCServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "MessageStream":
      return BidirectionalStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Protowire_KaspadRequest>(),
        responseSerializer: ProtobufSerializer<Protowire_KaspadResponse>(),
        interceptors: self.interceptors?.makeMessageStreamInterceptors() ?? [],
        observerFactory: self.messageStream(context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Protowire_RPCAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Protowire_RPCServerInterceptorFactoryProtocol? { get }

  func messageStream(
    requestStream: GRPCAsyncRequestStream<Protowire_KaspadRequest>,
    responseStream: GRPCAsyncResponseStreamWriter<Protowire_KaspadResponse>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Protowire_RPCAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Protowire_RPCServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Protowire_RPCServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Protowire_RPCServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "MessageStream":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Protowire_KaspadRequest>(),
        responseSerializer: ProtobufSerializer<Protowire_KaspadResponse>(),
        interceptors: self.interceptors?.makeMessageStreamInterceptors() ?? [],
        wrapping: { try await self.messageStream(requestStream: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

internal protocol Protowire_RPCServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'messageStream'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMessageStreamInterceptors() -> [ServerInterceptor<Protowire_KaspadRequest, Protowire_KaspadResponse>]
}

internal enum Protowire_RPCServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "RPC",
    fullName: "protowire.RPC",
    methods: [
      Protowire_RPCServerMetadata.Methods.messageStream,
    ]
  )

  internal enum Methods {
    internal static let messageStream = GRPCMethodDescriptor(
      name: "MessageStream",
      path: "/protowire.RPC/MessageStream",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}
